firstname = input("Enter First Name: ")
lastname = input("Enter Last Name: ")
middlename = input("Enter Middle Name: ")
birthday = input("Enter Birthday: ")
gender = input("Enter Gender: ")
address = input("Enter Address: ")
course = input("Enter Course: ")
yearlevel = input("Enter Year Level: ")
print()
print()
print("First Name:", firstname)
print("Last Name:", lastname)
print("Middle Name:", middlename)
print("Birthday:", birthday)
print("Gender:", gender)
print("Address:", address)
print("Course:", course)
print("Year Level:", yearlevel)
